### ISSUE TITLE
参数错误

### ISSUE THREAD

**Issue by gaolinlin12138** [plw-study/Reproduction_of_MCAN#4]
我在运行的时候出现了这种错误：
Traceback (most recent call last):
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\air\execution\_internal\event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\_private\worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(OSError): ray::TrainALL.train() (pid=39604, ip=127.0.0.1, actor_id=53377572bd846b9bcb0f4f8801000000, repr=<MCAN_reproduction.TrainALL object at 0x000002451D56CF70>)
  File "python\ray\_raylet.pyx", line 1889, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1830, in ray._raylet.execute_task.function_executor
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\_private\function_manager.py", line 724, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\tune\trainable\trainable.py", line 334, in train
    raise skipped from exception_cause(skipped)
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\tune\trainable\trainable.py", line 331, in train
    result = self.step()
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\yaoyanjiance\MCAN\Reproduction_of_MCAN-main\MCAN_reproduction.py", line 1157, in step
    test_acc = self.train_one_time()
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\yaoyanjiance\MCAN\Reproduction_of_MCAN-main\MCAN_reproduction.py", line 998, in train_one_time
    for i, train_data in enumerate(self.train_loader):
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\torch\utils\data\dataloader.py", line 444, in __iter__
    return self._get_iterator()
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\torch\utils\data\dataloader.py", line 390, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\207\AppData\Roaming\Python\Python38\site-packages\torch\utils\data\dataloader.py", line 1077, in __init__
    w.start()
  File "C:\Users\207\.conda\envs\MCAN-main\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\207\.conda\envs\MCAN-main\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\207\.conda\envs\MCAN-main\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\207\.conda\envs\MCAN-main\lib\multiprocessing\popen_spawn_win32.py", line 73, in __init__
    hp, ht, pid, tid = _winapi.CreateProcess(
OSError: [WinError 87] 参数错误。
请问这种错误应该怎么改进？

**Comment by 184446223** [comment]
> 我在运行时的时候出现了这种错误： Traceback (most recent call last): 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\air\execution_internal\event_manager.py”, 第 110 行，在 resolve_future result = ray.get(future) 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray_private\auto_init_hook.py”, 第 21 行，在 auto_init_wrapper 中 返回 fn(*args, **kwargs) 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray_private\client_mode_hook.py”, 第 103 行，在 wrapper 中 返回 func(*args, **kwargs) 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray_private\worker.py”，第 2667 行，在获取 值中，debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout) 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray_private\worker.py”，第 864 行，在 get_objects 中 引发 value.as_instanceof_cause() ray.exceptions.RayTaskError(OSError): ray::TrainALL.train() (pid=39604, ip=127.0.0.1, actor_id=53377572bd846b9bcb0f4f8801000000, repr=<MCAN_reproduction.TrainALL object at 0x000002451D56CF70>) 文件“python\ray_raylet.pyx”，第 1889 行，在 ray._raylet.execute_task 文件“python\ray_raylet.pyx”，第 1830 行，在 ray._raylet.execute_task.function_executor 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray_private\function_manager.py”，第 724 行，在 actor_method_executor 返回方法（__ray_actor，*args，**kwargs） 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\util\tracing\tracing_helper.py”，第 467 行，在 _resume_span 返回方法（self，*_args，**_kwargs） 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\tune\trainable\trainable.py”, 第 334 行，在训练中 引发从 exception_cause(skipped) 中跳过的 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\tune\trainable\trainable.py”, 第 331 行，在训练中 结果 = self.step() 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\util\tracing\tracing_helper.py”, 第 467 行，在 _resume_span 返回方法(self, *_args, **_kwargs) 文件“D:\yaoyanjiance\MCAN\Reproduction_of_MCAN-main\MCAN_reproduction.py”, 第 1157 行，在步骤 test_acc = self.train_one_time() 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\ray\util\tracing\tracing_helper.py”, 第 467 行, 在 _resume_span 返回方法 (self, *_args, **_kwargs) 文件“D:\yaoyanjiance\MCAN\Reproduction_of_MCAN-main\MCAN_reproduction.py”, 第 998 行, 在 train_one_time for i, train_data 在 enumerate(self.train_loader) 中: 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\torch\utils\data\dataloader.py”，第 444 行，位于**iter** 返回 self._get_iterator() 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\torch\utils\data\dataloader.py”，第 390 行，在 _get_iterator 中 返回 _MultiProcessingDataLoaderIter(self) 文件“C:\Users\207\AppData\Roaming\Python\Python38\site-packages\torch\utils\data\dataloader.py”，第 1077 行，在**init** w.start() 文件“C:\Users\207.conda\envs\MCAN-main\lib\multiprocessing\process.py”，第 121 行，在 start self._popen = self._Popen(self) 文件“C:\Users\207.conda\envs\MCAN-main\lib\multiprocessing\context.py”，第 224 行，在 _Popen 中 返回_default_context.get_context().Process._Popen(process_obj) 文件“C:\Users\207.conda\envs\MCAN-main\lib\multiprocessing\context.py”，第 327 行，在 _Popen 返回 Popen(process_obj) 文件“C:\Users\207.conda\envs\MCAN-main\lib\multiprocessing\popen_spawn_win32.py”，第 73 行， in **init** hp, ht, pid, tid = _winapi.CreateProcess( OSError: [WinError 87] 参数错误。 请问这种错误应该怎么改进？

请问您复现出来推特数据集的结果了吗?
