### ISSUE TITLE
安装环境

### ISSUE THREAD

**Issue by helloyournam** [plw-study/Reproduction_of_MCAN#6]
为什么我运行那个安装mcan,py文件有报错。有人可以解答我的疑问吗。谢谢
View detailed results here: C:/Users/qgxiao/ray_results/twitter-experiment
2024-11-10 22:55:22,356	WARNING trial.py:648 -- The path to the trial log directory is too long (max length: 260. Consider using `trial_dirname_creator` to shorten the path. Path: C:\Users\qgxiao\AppData\Local\Temp\ray\session_2024-11-10_22-55-13_280983_13204\artifacts\2024-11-10_22-55-22\twitter-experiment\driver_artifacts\TrainALL_cf814_00000_0_FREEZE_BERT=False,FREEZE_VGG=False,ablation=bert_dct_vgg_fusion,bert_learning_rate=0.0001,bert_model_name=b_2024-11-10_22-55-22
Traceback (most recent call last):
  File "D:\anaconda3\envs\dyxiao\lib\pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\qgxiao\\AppData\\Local\\Temp\\ray\\session_2024-11-10_22-55-13_280983_13204\\artifacts\\2024-11-10_22-55-22\\twitter-experiment\\driver_artifacts\\TrainALL_cf814_00000_0_FREEZE_BERT=False,FREEZE_VGG=False,ablation=bert_dct_vgg_fusion,bert_learning_rate=0.0001,bert_model_name=b_2024-11-10_22-55-22'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\qgxiao\PycharmProjects\python1\Reproduction_of_MCAN-main\MCAN_reproduction.py", line 1263, in <module>
    analysis = tune.run(
  File "D:\anaconda3\envs\dyxiao\lib\site-packages\ray\tune\tune.py", line 1001, in run
    runner.step()
  File "D:\anaconda3\envs\dyxiao\lib\site-packages\ray\tune\execution\tune_controller.py", line 683, in step
    self._maybe_add_actors()
  File "D:\anaconda3\envs\dyxiao\lib\site-packages\ray\tune\execution\tune_controller.py", line 861, in _maybe_add_actors
    self._schedule_trial_actor(trial_to_run)
  File "D:\anaconda3\envs\dyxiao\lib\site-packages\ray\tune\execution\tune_controller.py", line 975, in _schedule_trial_actor
    trial.init_local_path()
  File "D:\anaconda3\envs\dyxiao\lib\site-packages\ray\tune\experiment\trial.py", line 654, in init_local_path

    logdir_path.mkdir(parents=True, exist_ok=True)
  File "D:\anaconda3\envs\dyxiao\lib\pathlib.py", line 1293, in mkdir
    self.mkdir(mode, parents=False, exist_ok=exist_ok)
  File "D:\anaconda3\envs\dyxiao\lib\pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\qgxiao\\AppData\\Local\\Temp\\ray\\session_2024-11-10_22-55-13_280983_13204\\artifacts\\2024-11-10_22-55-22\\twitter-experiment\\driver_artifacts\\TrainALL_cf814_00000_0_FREEZE_BERT=False,FREEZE_VGG=False,ablation=bert_dct_vgg_fusion,bert_learning_rate=0.0001,bert_model_name=b_2024-11-10_22-55-22'

**Comment by helloyournam** [comment]
我运行那个安装文件，但有的包一直装不上，太古早了。是ray安装的问题吗，我用的2.10.0，有人可以解答一下吗，你们怎么解决的。谢谢
